version: "3.9"

services:
  flask-app:
    container_name: flask-app
    build: .
    # Dans le cas où vous auriez besoin d'un restart automatique en cas de crash
    restart: unless-stopped

    # On mappe un port local vers le port interne Flask (5000).
    ports:
      - "5000:5000"

    # On définit un volume pour persister les données SQLite, monté dans /app/data
    volumes:
      - flask_data:/app/data

    # Variable d'environnement pour localiser la base de données
    environment:
      - DATABASE_FILE=/app/data/data.db

volumes:
  flask_data:
