---
- name: Déployer l'application Flask sur le VPS
  hosts: vps
  become: true  # si vous avez besoin d'élévation de privilèges pour exécuter Docker

  tasks:
    - name: Vérifier si le dossier /home/rocky/swagconfig existe
      stat:
        path: /home/rocky/swagconfig
      register: swagconfig_dir

    - name: Mettre à jour les fichiers dans swag/proxy-confs
      copy:
        src: ../swag/proxy-confs/
        dest: /home/rocky/swagconfig/nginx/proxy-confs/
        owner: rocky
        group: rocky
        mode: '0755'
        remote_src: no
      when: swagconfig_dir.stat.exists

    - name: Ajouter swag au réseau apisight_network
      command: docker network connect app_flask_apisight_network swag
      ignore_errors: true  # si jamais on n'a pas encore déployé, on ignore les erreurs
    
    - name: relancer le conteneur swag
      command: docker restart swag
      ignore_errors: true  # si jamais on n'a pas encore déployé, on ignore les erreurs
    